# Generated by Django 5.2.4 on 2025-08-06 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttestsuite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testcasehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='projecttestsuite',
            index=models.Index(fields=['project'], name='testcase_hi_project_4294cb_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttestsuite',
            index=models.Index(fields=['test_suite_name'], name='testcase_hi_test_su_bb7988_idx'),
        ),
        migrations.AddIndex(
            model_name='testcasehistory',
            index=models.Index(fields=['test_suite'], name='testcase_hi_test_su_b7de14_idx'),
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['user'], name='testcase_hi_user_id_4c66b6_idx'),
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['project_name'], name='testcase_hi_project_5532b2_idx'),
        ),
    ]
